# Generated by Django 5.2 on 2026-06-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_carrier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
