# Generated by Django 5.2 on 2026-05-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('coupon_code', models.CharField(blank=True, max_length=50)),
                ('link_url', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BrandStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='brand/')),
                ('heading', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('cta_label', models.CharField(default='Shop Now', max_length=50)),
                ('cta_url', models.CharField(default='/collections/', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='hero/')),
                ('headline', models.CharField(max_length=100)),
                ('sub_headline', models.CharField(blank=True, max_length=200)),
                ('cta1_label', models.CharField(default='Shop Now', max_length=50)),
                ('cta1_url', models.CharField(default='/collections/', max_length=200)),
                ('cta2_label', models.CharField(blank=True, max_length=50)),
                ('cta2_url', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(blank=True, help_text='Heroicon name or custom SVG class', max_length=100)),
                ('icon_svg', models.TextField(blank=True, help_text='Paste raw SVG markup')),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
